//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.8.4084.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.daisy.org/z3986/2005/ncx/", IsNullable=false)]
public partial class ncx {
    
    private ncxHead headField;
    
    private ncxDocTitle docTitleField;
    
    private ncxNavMap navMapField;
    
    private string versionField;
    
    /// <remarks/>
    public ncxHead head {
        get {
            return this.headField;
        }
        set {
            this.headField = value;
        }
    }
    
    /// <remarks/>
    public ncxDocTitle docTitle {
        get {
            return this.docTitleField;
        }
        set {
            this.docTitleField = value;
        }
    }
    
    /// <remarks/>
    public ncxNavMap navMap {
        get {
            return this.navMapField;
        }
        set {
            this.navMapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxHead {
    
    private ncxHeadMeta metaField;
    
    /// <remarks/>
    public ncxHeadMeta meta {
        get {
            return this.metaField;
        }
        set {
            this.metaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxHeadMeta {
    
    private string nameField;
    
    private string contentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxDocTitle {
    
    private string textField;
    
    /// <remarks/>
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxNavMap {
    
    private ncxNavMapNavPoint navPointField;
    
    /// <remarks/>
    public ncxNavMapNavPoint navPoint {
        get {
            return this.navPointField;
        }
        set {
            this.navPointField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxNavMapNavPoint {
    
    private ncxNavMapNavPointNavLabel navLabelField;
    
    private ncxNavMapNavPointContent contentField;
    
    private ncxNavMapNavPointNavPoint[] navPointField;
    
    private string idField;
    
    private byte playOrderField;
    
    /// <remarks/>
    public ncxNavMapNavPointNavLabel navLabel {
        get {
            return this.navLabelField;
        }
        set {
            this.navLabelField = value;
        }
    }
    
    /// <remarks/>
    public ncxNavMapNavPointContent content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("navPoint")]
    public ncxNavMapNavPointNavPoint[] navPoint {
        get {
            return this.navPointField;
        }
        set {
            this.navPointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte playOrder {
        get {
            return this.playOrderField;
        }
        set {
            this.playOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxNavMapNavPointNavLabel {
    
    private string textField;
    
    /// <remarks/>
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxNavMapNavPointContent {
    
    private string srcField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string src {
        get {
            return this.srcField;
        }
        set {
            this.srcField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxNavMapNavPointNavPoint {
    
    private ncxNavMapNavPointNavPointNavLabel navLabelField;
    
    private ncxNavMapNavPointNavPointContent contentField;
    
    private ncxNavMapNavPointNavPointNavPoint[] navPointField;
    
    private string idField;
    
    private ushort playOrderField;
    
    /// <remarks/>
    public ncxNavMapNavPointNavPointNavLabel navLabel {
        get {
            return this.navLabelField;
        }
        set {
            this.navLabelField = value;
        }
    }
    
    /// <remarks/>
    public ncxNavMapNavPointNavPointContent content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("navPoint")]
    public ncxNavMapNavPointNavPointNavPoint[] navPoint {
        get {
            return this.navPointField;
        }
        set {
            this.navPointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort playOrder {
        get {
            return this.playOrderField;
        }
        set {
            this.playOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxNavMapNavPointNavPointNavLabel {
    
    private string textField;
    
    /// <remarks/>
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxNavMapNavPointNavPointContent {
    
    private string srcField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string src {
        get {
            return this.srcField;
        }
        set {
            this.srcField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxNavMapNavPointNavPointNavPoint {
    
    private ncxNavMapNavPointNavPointNavPointNavLabel navLabelField;
    
    private ncxNavMapNavPointNavPointNavPointContent contentField;
    
    private ncxNavMapNavPointNavPointNavPointNavPoint[] navPointField;
    
    private string idField;
    
    private ushort playOrderField;
    
    /// <remarks/>
    public ncxNavMapNavPointNavPointNavPointNavLabel navLabel {
        get {
            return this.navLabelField;
        }
        set {
            this.navLabelField = value;
        }
    }
    
    /// <remarks/>
    public ncxNavMapNavPointNavPointNavPointContent content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("navPoint")]
    public ncxNavMapNavPointNavPointNavPointNavPoint[] navPoint {
        get {
            return this.navPointField;
        }
        set {
            this.navPointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort playOrder {
        get {
            return this.playOrderField;
        }
        set {
            this.playOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxNavMapNavPointNavPointNavPointNavLabel {
    
    private string textField;
    
    /// <remarks/>
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxNavMapNavPointNavPointNavPointContent {
    
    private string srcField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string src {
        get {
            return this.srcField;
        }
        set {
            this.srcField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxNavMapNavPointNavPointNavPointNavPoint {
    
    private ncxNavMapNavPointNavPointNavPointNavPointNavLabel navLabelField;
    
    private ncxNavMapNavPointNavPointNavPointNavPointContent contentField;
    
    private ncxNavMapNavPointNavPointNavPointNavPointNavPoint[] navPointField;
    
    private string idField;
    
    private ushort playOrderField;
    
    /// <remarks/>
    public ncxNavMapNavPointNavPointNavPointNavPointNavLabel navLabel {
        get {
            return this.navLabelField;
        }
        set {
            this.navLabelField = value;
        }
    }
    
    /// <remarks/>
    public ncxNavMapNavPointNavPointNavPointNavPointContent content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("navPoint")]
    public ncxNavMapNavPointNavPointNavPointNavPointNavPoint[] navPoint {
        get {
            return this.navPointField;
        }
        set {
            this.navPointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort playOrder {
        get {
            return this.playOrderField;
        }
        set {
            this.playOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxNavMapNavPointNavPointNavPointNavPointNavLabel {
    
    private string textField;
    
    /// <remarks/>
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxNavMapNavPointNavPointNavPointNavPointContent {
    
    private string srcField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string src {
        get {
            return this.srcField;
        }
        set {
            this.srcField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxNavMapNavPointNavPointNavPointNavPointNavPoint {
    
    private ncxNavMapNavPointNavPointNavPointNavPointNavPointNavLabel navLabelField;
    
    private ncxNavMapNavPointNavPointNavPointNavPointNavPointContent contentField;
    
    private string idField;
    
    private byte playOrderField;
    
    /// <remarks/>
    public ncxNavMapNavPointNavPointNavPointNavPointNavPointNavLabel navLabel {
        get {
            return this.navLabelField;
        }
        set {
            this.navLabelField = value;
        }
    }
    
    /// <remarks/>
    public ncxNavMapNavPointNavPointNavPointNavPointNavPointContent content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte playOrder {
        get {
            return this.playOrderField;
        }
        set {
            this.playOrderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxNavMapNavPointNavPointNavPointNavPointNavPointNavLabel {
    
    private string textField;
    
    /// <remarks/>
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.daisy.org/z3986/2005/ncx/")]
public partial class ncxNavMapNavPointNavPointNavPointNavPointNavPointContent {
    
    private string srcField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string src {
        get {
            return this.srcField;
        }
        set {
            this.srcField = value;
        }
    }
}
